# Generated by Django 3.0.6 on 2020-05-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='Q1',
            field=models.ForeignKey(default='no answer', on_delete=django.db.models.deletion.CASCADE, related_name='Q1', to='reviews.Question'),
        ),
        migrations.AddField(
            model_name='review',
            name='Q2',
            field=models.ForeignKey(default='no answer', on_delete=django.db.models.deletion.CASCADE, related_name='Q2', to='reviews.Question'),
        ),
        migrations.AddField(
            model_name='review',
            name='Q3',
            field=models.ForeignKey(default='no answer', on_delete=django.db.models.deletion.CASCADE, related_name='Q3', to='reviews.Question'),
        ),
        migrations.AddField(
            model_name='review',
            name='Q4',
            field=models.ForeignKey(default='no answer', on_delete=django.db.models.deletion.CASCADE, related_name='Q4', to='reviews.Question'),
        ),
        migrations.AddField(
            model_name='review',
            name='Q5',
            field=models.ForeignKey(default='no answer', on_delete=django.db.models.deletion.CASCADE, related_name='Q5', to='reviews.Question'),
        ),
    ]
